
//! Autogenerated weights for `pallet_template`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-01-31, STEPS: `20`, REPEAT: 100, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/node-template
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_template
// --extrinsic
// *
// --steps
// 20
// --repeat
// 100
// --raw
// --output
// ./

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

pub trait WeightInfo {
	fn do_something() -> Weight;
}

/// Weight functions for `pallet_template`.
pub struct TemplateWeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for TemplateWeightInfo<T> {
	// Storage: TemplateModule Something (r:0 w:1)
	fn do_something() -> Weight {
		(18_945_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}
